### PR TITLE
add useService to react template

### PR DESCRIPTION
**Pull request by redappleorigin**
xstate's spawn is fine calling the xstate-compiled machine, useService was not.

### CODE REVIEW

**Comment by mattpocock** [comment]
Tested, and working. @redappleorigin could you add a changeset with `yarn changeset` in root?

**Comment by mattpocock** [comment]
Once that's in I'll merge. Thanks for this, great work 👍

**Comment by redappleorigin** [comment]
Yes sir, I just need to figure out how to do that first.

**Comment by redappleorigin** [comment]
@mattpocock let me know if I did this correctly.

**Comment by mattpocock** [comment]
@redappleorigin Have released this in the latest 'next' version

**Comment by FredyC** [comment]
@redappleorigin Can you please help me out how is this intended to be used?  https://github.com/mattpocock/xstate-codegen/issues/48

**Pull request merged**
