### PR TITLE
Fix typos in readme, `@xtate` -> `@xstate` × 2

### PR DESCRIPTION
**Pull request by jen729w**
Let's see if I get this right this time.

### CODE REVIEW

**Comment by jen729w** [comment]
Heyyyy check me out with the changeset. 😎

**Comment by davidkpiano** [comment]
It's actually `@xtato`, an upcoming potato-based state management library 🥔

**Comment by jen729w** [comment]
Oh man, I'm British. Don't tease me like that.

**Comment by mattpocock** [comment]
_XTATERS? WHAT'S... XTATERS?_

**Comment by mattpocock** [comment]
Nice, I'll merge this. There's actually a duplicated readme inside the package file too, but I'll fix it locally meself.

Thanks @jen729w!

**Comment by mattpocock** [comment]
Available on latest version of the 'next' branch

**Pull request merged**
