### PR TITLE
Rewrite to ts morph

### PR DESCRIPTION
**Pull request by Andarist**

### CODE REVIEW

**Comment by mattpocock** [comment]
Very exciting. I've added a complex machine test case into master which tests parallel states, nested states etc. When I tried it on this branch, the tests failed. Could you pull that into this PR and try to make it pass?

**Comment by mattpocock** [comment]
Found a machine in my work repo that fails on the branch. I've added it to master - pull it in to see the changes. Copying here as well in case merging is a PITA:

```
import { Machine, send, assign } from '@xstate/compiled';

type Attendee = {
  name: string;
  email: string;
  id: string;
};

interface Context {
  initialAttendees: Attendee[];
  attendeesToCreate: Attendee[];
  attendeesInList: Attendee[];
  attendeeIdsToDelete: Set<string>;
}

type Event =
  | { type: 'ADD_ATTENDEE'; name: string; email: string }
  | { type: 'EDIT_ATTENDEE'; id: string; name: string; email: string }
  | { type: 'REMOVE_ATTENDEE'; id: string }
  | {
      type: 'GO_BACK';
    }
  | {
      type: 'SUBMIT';
    }
  | {
      type: 'REPORT_ERROR';
    }
  | {
      type: 'done.invoke.createViewing';
      data: string;
    };

const assignAttendee = assign<
  Context,
  Extract<Event, { type: 'ADD_ATTENDEE' }>
>((context, event) => {
  const newAttendee = {
    id: '1',
    email: event.email,
    name: event.name,
  };
  return {
    attendeesToCreate: [...context.attendeesToCreate, newAttendee],
    attendeesInList: [...context.attendeesInList, newAttendee],
  };
});

export const addViewingAttendeesMachine = Machine<
  Context,
  Event,
  'addViewingAttendees'
>({
  id: 'addViewingAttendees',
  context: {
    attendeesToCreate: [],
    attendeeIdsToDelete: new Set(),
    initialAttendees: [],
    attendeesInList: [],
  },
  initial: 'idle',
  states: {
    idle: {
      on: {
        GO_BACK: [
          {
            cond: 'inCreateMode',
            actions: 'goToPrevPage',
          },
          {
            cond: 'inEditMode',
            actions: 'goBackToEditOverview',
          },
        ],
        ADD_ATTENDEE: [
          {
            actions: [assignAttendee],
          },
        ],
        REMOVE_ATTENDEE: {
          actions: [
            assign((context, event) => {
              let attendeeIdsToDelete = new Set(context.attendeeIdsToDelete);
              attendeeIdsToDelete.add(event.id);

              return {
                attendeeIdsToDelete,
                attendeesInList: context.attendeesInList.filter(
                  (attendee) => attendee.id !== event.id,
                ),
                attendeesToCreate: context.attendeesToCreate.filter(
                  (attendee) => attendee.id !== event.id,
                ),
              };
            }),
          ],
        },
        EDIT_ATTENDEE: [
          {
            actions: [
              assign((context, event) => {
                const attendeeWasOnInitialList = context.initialAttendees.some(
                  (attendee) => {
                    return attendee.id === event.id;
                  },
                );

                let attendeeIdsToDelete = new Set(context.attendeeIdsToDelete);
                if (attendeeWasOnInitialList) {
                  attendeeIdsToDelete.add(event.id);
                }

                return {
                  attendeeIdsToDelete,
                  attendeesToCreate: [
                    ...context.attendeesToCreate.filter(
                      (attendee) => attendee.id !== event.id,
                    ),
                    { email: event.email, id: event.id, name: event.name },
                  ],
                  attendeesInList: context.attendeesInList.map((attendee) => {
                    if (attendee.id === event.id) {
                      return {
                        id: event.id,
                        name: event.name,
                        email: event.email,
                      };
                    }
                    return attendee;
                  }),
                };
              }),
            ],
          },
        ],
      },
      initial: 'initial',
      states: {
        initial: {
          on: {
            SUBMIT: [
              {
                cond: 'hasNotAddedAnyInvitees',
                target: 'isWarningThatUserIsNotInvitingAnyone',
              },
              {
                cond: 'currentFormStateIsValidAndInCreateMode',
                target: '#creating',
              },
              {
                cond: 'currentFormStateIsValidAndInUpdateMode',
                target: '#updating',
              },
            ],
          },
        },
        isWarningThatUserIsNotInvitingAnyone: {
          on: {
            ADD_ATTENDEE: {
              actions: [assignAttendee],
              target: 'initial',
            },
            SUBMIT: [
              {
                cond: 'currentFormStateIsValidAndInCreateMode',
                target: '#creating',
              },
              {
                cond: 'currentFormStateIsValidAndInUpdateMode',
                target: '#updating',
              },
            ],
          },
        },
        errored: {},
      },
    },
    creating: {
      id: 'creating',
      invoke: {
        src: 'createViewing',
        onDone: {
          target: 'idle',
          actions: 'goToSuccessPage',
        },
        onError: {
          target: 'idle.errored',
        },
      },
    },
    updating: {
      id: 'updating',
      initial: 'checkingAttendees',
      states: {
        checkingAttendees: {
          always: [
            {
              cond: (context) =>
                Array.from(context.attendeeIdsToDelete).length > 0,
              target: 'deletingExcessGuests',
            },
            {
              cond: (context) => context.attendeesToCreate.length > 0,
              target: 'creatingNewAndEditedGuests',
            },
            {
              target: 'complete',
            },
          ],
        },
        deletingExcessGuests: {
          invoke: {
            src: 'deleteExcessGuests',
            onDone: [
              {
                cond: (context) => context.attendeesToCreate.length > 0,
                target: 'creatingNewAndEditedGuests',
              },
              {
                target: 'complete',
              },
            ],
            onError: 'errored',
          },
        },
        creatingNewAndEditedGuests: {
          invoke: {
            src: 'createNewGuests',
            onDone: [
              {
                target: 'complete',
              },
            ],
            onError: 'errored',
          },
        },
        errored: {
          entry: send({
            type: 'REPORT_ERROR',
          }),
        },
        complete: {
          type: 'final',
          entry: ['goBackToEditOverview', 'showToastWithChangesSaved'],
        },
      },
    },
  },
});

```

**Comment by Andarist** [comment]
Ah, i knew this has to happen - was just hoping that a little bit later :P i think i need to bring back the schema-based approach, just need to make the logic more tolerant to matching any state-likes (previously ive tried to be too strict about compound/atomic/etc). Will work on that today/tomorrow - hopefully wont take too long. That approach will allow me to just skip over extracting context which is problematic here

**Comment by FredyC** [comment]
@Andarist Do you think you will find time to continue on this? I am not sure if this PR solved it specifically, but missing support for path aliases from `tsconfig.json` pains me. Or if you can give some pointers on the next steps, I can attempt to finish it by myself.

**Comment by Andarist** [comment]
> @Andarist Do you think you will find time to continue on this?

I have actually got back to working on this already earlier this week.

> I am not sure if this PR solves it specifically, but missing support for path aliases from tsconfig.json pains me.

It should because file resolution is delegated to TS and it's tsconfig.json-aware. Unless you would have some very specific setup for which the current logic fails to locate the `tsconfig.json` correctly - that would be solvable with an additiona `tsconfigPath` option or smth but I don't expect that this will be required.

> Or if you can give some pointers on the next steps, I can attempt to finish it by myself.

We could definitely use some help if you'd like to collaborate on this. I have very limited time to work on all of this (2 kids at home 😉) and there are some things to figure out in relation to IDE, linting etc. We have some additional plans to restructure this tool plus provide VSCode extension - gonna be posting more about this soon but the implementation definitely won't happen over night.

**Comment by Andarist** [comment]
I've pushed out my recent work on this - it works for the majority of cases, existing tests pass. However, if I fail to extract things the DX ain't great because no helpful errors are printed to the user. It's very important to get this right as without that this is not really that usable.

I've also dropped temporarily support for `choose` since based on type-info alone I could not access used guards/actions within it. I've experimented with some kinda crazy types that could replace XState's `choose` and which would enable me to extract the required information at the type-level. Here it is:
[TS playground](https://www.typescriptlang.org/play?#code/PQkKDAXBPAHBTABAFQE7QDwEECMj4Aek8AdgCYDOiAhidADSJYBM+RplNdjAwtZAGMAFogC8iEvABu8VAD4xYRMqZ5CxclRZKVAflU7lALkR9BQiDASIActVSoA9gHdqAIwA2SUWAA+iCkhUAEsSAHM-CQBXAFs3WUi3YLDQyETHRy9aSzgkOwcXACVqZ2wFH38ACiw2DU4AbQBdRH0mxBNJGVQASkjq2o4qfKdXTyR9Go7pWV6qgG96gGlEUMQAa3hoRwAzJkaTLCXm9UHEADEokgFIYMcSQxVHp6eJo4fnj5UTYaKS7CO5ABfboAbhy1h+pRqJ00XGg5QeaEwWEYTUYkOKULkcggoHAYFSsm21AESAAojISJAAPJuABW8GuiDmiCs8BMgRC4UQgIgZEZHnsSDZiAAyqEwl5qagsA5qJhkOUUG1-MgwWB+QJBahhbkmNdbiQLlcbncMMgeHdiERGMgKaRIANYfaqbSGdclZUBFb1CYLT6bfhKZA-S7IN0xAopI5gmQwYTUMTSfrTSQ3YzIObLVT1Law07OGH0x7mQ82RyghKwY9CIzdAcDXdjY2SFmA5A88G5NWVPVHJAhLIK1ywvs4WDeRqBULWXqsC22znA3bgwWqEX6RmlZyJYh-PPU8XM-6lx2UGGFPuW83U4vrWeVw7u3zpzrZ9YD4aKHfc+fVzDC2DI8lXFcIpRlOVkQXE9707J9nynLUZxFbMyGCVMAAUdTQgR+HgH9l3zAD1yAzcS3EL12z9bNYKDB1Q2DCNRAUNwMiye4wBARAyEceAKBIAByR1oHgR0KCiWBYEcVBHRZcsAkrcIQUQeoNmgYcJTHWhoB5RDtV1axUPQw0CIfIj2GdUj3UgbdFLCPdTDuNDMOw4JcOIUy4KpBQIATJMkB4IQMgoeAjMgM0YN-R8qTXRAN2shQ5geb1yHrRzyGMiKaKii8e2UElUwoBtCs8v8nwnXyc0TEkAqCxwQs-LL2y8x1iLiqyt1ixq0zI49ssIrtS0eeSBIIQI8IAOmEYL4AEvLEBSygDkgjBApmsKmtPFrsQqvSZ22S4WwWuqQtK6LWoswCHWAyjNGW1B5VWk7Qqc9DNto87sW6Ew1vq+BurO3LwQCpzv1FeAPG2W1+rM-9LpI67eqVWUHswJLHkWtKwpMyKBqfB4Cq-Yqv0BrsJxxPa3wOk1DWOmbmAwcHIdi1CwYhqGUBh7boeasqYra+Kt1upbbHsEZGfZuRvsQaNY3VFLAhoMQ6b+5hKnqFlFpMIS+MgATGEJu4ipUgTtgyfXEAEtx7AE5pAUYTWnO12A3LWABJPWDZbY2BIAR2cWQYAEnlGl6CAgA)

This relies on type inference so explicit type params for `TContext` and `TEvent` are not allowed with this. I need to think about the implications of that.

**Comment by VanTanev** [comment]
Was this closed accidentally?

**Comment by Andarist** [comment]
@VanTanev no, this branch was created on my fork and I've pushed it out to the origin and created this PR: https://github.com/mattpocock/xstate-codegen/pull/78 , in the hope to fix the problem with snapshot releases that I've tried to add to this. Unfortunately, that didn't fix the problem with those releases 😬

**Pull request closed without merging**
