### PR TITLE
Support delays in machine options

### LINKED ISSUE #53: Machine options lack support for delays
https://xstate.js.org/docs/guides/delays.html#delayed-transitions

### PR DESCRIPTION
**Pull request by FredyC**
That wasn't as hard as I expected, you have the solid groundwork in there. Hopefully, I did not miss something, but tests are passing.

Fixes #53

### CODE REVIEW

**Comment by mattpocock** [comment]
This is great.

One thing which I had to double-check in my head: delays are not like entry actions. In a condition triggered by a delay, there's no `event` which we need to type in order to get right.

**Comment by FredyC** [comment]
@mattpocock Is is that important? I mean I tried what kind of event is happening there, but it's just an internal one.

https://codesandbox.io/s/tender-bush-9kuz0?file=/src/index.ts

**Comment by mattpocock** [comment]
@FredyC You're right. To clarify above, I was saying it _wasn't_ something we needed to take into account. It's an internal event we can feel free to not type strongly.

Still early here!

**Comment by FredyC** [comment]
Ah, totally misread you :) But in a way, I suppose it could be at least typed to `AnyEvent`, right now it's `never` which is technically incorrect.

**Review by mattpocock — APPROVED** [review]

**Comment by mattpocock** [comment]
I think `never` is actually better than `AnyEvent`, since you're never likely to want to use that internal xstate event. If that changes, we can revisit this. Happy to merge this, nice work :)

**Comment by FredyC** [comment]
Alright, makes sense. I kinda managed to generate this locally, but that's not correct either because the name of the event should have the actual number, not the name of delay. I guess that would be more complicated and probably not worth it.

```ts
        delayedCond: (
          context: TContext,
          event:
            Extract<TEvent,
            | { type: 'xstate.guard' }
            | { type: 'xstate.after(REQUIRED_DELAY)#(machine).idle' }
            >
          ) => boolean;
```

Merge away :)

**Comment by FredyC** [comment]
Actually, I had the wrong example. With the named delay, the name is used in the event name. But obviously, users would need to include such a specific event in the machine events and that's unlikely someone would no, cannot even imagine the reason.

**Pull request merged**
